### ISSUE TITLE
Css doesn't exist?

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/css-validation-fixes#1]
Markbot says that my css file and folder don't exist when they do! I've tried changing it in atom AND through github and it still hasn't changed anything. Any advice? (I'm also using a PC, not Mac)
@hellachella

**Comment by hellachella** [comment]
It does indeed exist. push and commit again and see what happens. PC is more finicky with Markbot. sometimes we have to grade manually for it.

**Comment by emahadzimustafic** [comment]
Hi Chelle. I've renamed it for a second time and it worked, but now it's saying that it doesn't follow the naming conventions (it says it's formatted as "css/ main.css" but it's actually "css/main.css"). I've checked my code with a friend (mac user) and we have the same thing. I'm assuming it's because I'm using PC again

**Comment by emahadzimustafic** [comment]
Fixed it, thanks!
